name: yafva-jar

services:
  validator:
    restart: always
    container_name: yafva-jar
    image: yafva-jar:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./fhir:/home/yafva/.fhir
      - ./application.yaml:/app/application.yaml
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
